/**
 * Motion Task signals
 */
typedef enum
{
    SERIAL_TASK_INIT_SIG = EM_USER_SIG ,
	SERIAL_TASK_WAKEUP_LORA_SIG,
	SERIAL_TASK_LORA_READY_SIG,
    SERIAL_TASK_LPC_WAKEUP_TIMEOUT_SIG,
	SERIAL_TASK_XMIT_COMPLETED_SIG,
	SERIAL_TASK_RESET_WDT_SIG,
	SERIAL_TASK_SIG_COUNT
} MotionSignals_t;

/**
 * Tracker task signals
 */
typedef enum
{
    BEACON_BLE_INIT_SIG = SERIAL_TASK_SIG_COUNT,
	BLE_ANCHOR_TRACKER_DISCONNECTED_SIG,
	BLE_ANCHOR_TRACKER_CONNECTED_SIG,
	BLE_ANCHOR_START_SENDING_SERIAL_SIG,
	BLE_ANCHOR_LORA_READY_SIG,
	BLE_ANCHOR_LPC_WAKEUP_TIMEOUT_SIG,
	BLE_ANCHOR_SERIAL_XMIT_COMPLETED_SIG,
	BLE_ANCHOR_CONN_TIMEOUT_SIG,
	BLE_ANCHOR_DISCONNECT_TIMEOUT_SIG,
	BLE_ANCHOR_TRACKER_DATA_RECEIVED_SIG,
	BLE_ANCHOR_START_CONN_ADV_SIG,
	BLE_ANCHOR_RESET_WDT_SIG,
	BLE_ANCHOR_TPL5010_DONE_SIG,
	BLE_ANCHOR_REXT_CALCULATED_SIG,
    BEACON_SIG_COUNT
} BeaconSignals_t;
